### ISSUE TITLE
http://docs.metamask.io/ is having issues

### ISSUE THREAD

**Issue by Jon-Biz** [MetaMask/metamask-docs#67]
Only the home page is accessible, and that without css. All internal links return a 404.

**Comment by Jon-Biz** [comment]
No longer happening.

**Comment by Jon-Biz** [comment]
Still having issues, though the root page's css is now being retreived. While the navigation links don't respond, the documentation text can be reached by directly requesting the url.

It looks like some webpack bundled files aren't available on the server:

```
app.c0015350.js:1 GET http://docs.metamask.io/guide/assets/js/15.252932b0.js net::ERR_ABORTED 404 (Not Found)
a.e @ app.c0015350.js:1
v-988e000c @ app.c0015350.js:6
(anonymous) @ app.c0015350.js:6
c @ app.c0015350.js:8
(anonymous) @ app.c0015350.js:8
t.<computed> @ app.c0015350.js:8
s @ app.c0015350.js:6
a @ app.c0015350.js:6
(anonymous) @ app.c0015350.js:6
e @ app.c0015350.js:6
e @ app.c0015350.js:6
(anonymous) @ app.c0015350.js:6
C @ app.c0015350.js:6
beforeEnter @ app.c0015350.js:8
d @ app.c0015350.js:8
r @ app.c0015350.js:8
(anonymous) @ app.c0015350.js:8
(anonymous) @ app.c0015350.js:8
(anonymous) @ app.c0015350.js:8
d @ app.c0015350.js:8
r @ app.c0015350.js:8
(anonymous) @ app.c0015350.js:8
(anonymous) @ app.c0015350.js:8
(anonymous) @ app.c0015350.js:8
d @ app.c0015350.js:8
r @ app.c0015350.js:8
r @ app.c0015350.js:8
yt @ app.c0015350.js:8
St.confirmTransition @ app.c0015350.js:8
St.transitionTo @ app.c0015350.js:8
e.push @ app.c0015350.js:8
Nt.push @ app.c0015350.js:8
b @ app.c0015350.js:8
Bt @ app.c0015350.js:6
n @ app.c0015350.js:6
i._wrapper @ app.c0015350.js:6
Show 6 more frames
app.c0015350.js:1 Uncaught (in promise) ChunkLoadError: Loading chunk 15 failed.
(error: http://docs.metamask.io/guide/assets/js/15.252932b0.js)
    at Function.a.e (http://docs.metamask.io/assets/js/app.c0015350.js:1:1417)
    at v-988e000c (http://docs.metamask.io/assets/js/app.c0015350.js:6:65333)
    at http://docs.metamask.io/assets/js/app.c0015350.js:6:67559
    at c (http://docs.metamask.io/assets/js/app.c0015350.js:8:37784)
    at Generator._invoke (http://docs.metamask.io/assets/js/app.c0015350.js:8:37572)
    at Generator.t.<computed> [as next] (http://docs.metamask.io/assets/js/app.c0015350.js:8:38206)
    at s (http://docs.metamask.io/assets/js/app.c0015350.js:6:64884)
    at a (http://docs.metamask.io/assets/js/app.c0015350.js:6:67741)
    at http://docs.metamask.io/assets/js/app.c0015350.js:6:67800
    at new Promise (<anonymous>)
```

**Comment by BboyAkers** [comment]
Is this in production? If so I've tried in Chrome, and Edge and it seems to works just fine. what browser are you using and have you emptied your cache and hard reloaded?

**Comment by jennypollack** [comment]
Full functionality should be restored as of 3-4 hours ago, but let us know if you're still seeing issues.
